Laura Abondano
POLYGYNY THRESHOLD MODEL
========================================================

Install and load required packages to connect R and Netlogo:
```{r Loading required packages}
library(rJava)
library(JavaGD)
library(RNetLogo)
library(ggplot2)
```

To load modified Flocking model from Netlogo:
```{r Loading modified Flocking model from Netlogo}
nl.path <- "/Applications/NetLogo 5.0.5"
NLStart(nl.path, gui=FALSE)
nl.model <- "/Users/Bondi/Dropbox/UT-Austin/4th Semester/Agent Based Modelling/Abondano-ABMGitHub/PTM/PTM_R.nlogo"
# replace the path above with your own path the to Flocking.nlogo program
# must have the sql extension enables in NetLogo (not the R extension!!!)
NLLoadModel(nl.model)
```


```{r PTM typical graph}
female.rep.success <- function(simul,ticks,trees.seq,tree.distribution,dist.trees,num.males,num.fem,fem.min.resources){
  df.PTM <- data.frame(matrix(nrow=(length(trees.seq)),ncol=5))
  names(df.PTM) <- c("Initial.trees", "Average Resources", "Resources Distribution", "Mono.success", "Poly.success")
  for (i in 1:length(trees.seq)){
  trees <- trees.seq[i]
  NLCommand(paste("set total-trees ", trees), "setup")
  NLCommand(paste("set distance-trees ", dist.trees), "setup")
  # Distribution: 1 = uniform, 2 = clumped, 3 = random
  NLCommand(paste("set distribution ", tree.distribution), "setup")
  NLCommand(paste("set initial-males ", num.males), "setup")
  NLCommand(paste("set initial-females ", num.fem), "setup")
  NLCommand(paste("set female-min-resources ", fem.min.resources), "setup")
  NLCommand(paste("while [ticks < ", ticks),"] [go]") 
  monogamous.fem.success <- as.numeric(NLReport("sum mono-females-rep-success"))
  polygynous.fem.success <- as.numeric(NLReport("sum poly-females-rep-success"))
  average.resources.total <- as.numeric(NLReport("mean resource-abundance-list"))
  df.PTM[i,]<-c(trees, average.resources.total, tree.distribution, monogamous.fem.success, polygynous.fem.success)
  }   
  return(df.PTM)
}

trees.seq<-seq(100,500,50)
fem.mono.poly.uniform<-female.rep.success(1,100,trees.seq,1, 0.25, 24, 100, 10)
fem.mono.poly.clumped<-female.rep.success(1,100,trees.seq,2, 0.25, 24, 100, 10)
fem.mono.poly.random<-female.rep.success(1,100,trees.seq,3, 0.25, 24, 100, 10)
plot.1<-ggplot() + geom_smooth (data = fem.mono.poly.uniform, aes(x = Initial.trees, y = Mono.success), colour = "red", size = 2) + geom_smooth (data = fem.mono.poly.uniform, aes(x = Initial.trees, y = Poly.success), colour = "blue", size = 2) + geom_smooth (data = fem.mono.poly.clumped, aes(x = Initial.trees, y = Mono.success), colour = "orange", size = 2) + geom_smooth (data = fem.mono.poly.clumped, aes(x = Initial.trees, y = Poly.success), colour = "green", size = 2) + geom_smooth (data = fem.mono.poly.random, aes(x = Initial.trees, y = Mono.success), colour = "yellow", size = 2) + geom_smooth (data = fem.mono.poly.random, aes(x = Initial.trees, y = Poly.success), colour = "purple", size = 2) + xlab("Abundance of Resources") + ylab("Female Reproductive Success") + theme(axis.title=element_text(size=22), axis.text=element_text(size=14))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
plot.1
fem.mono.poly.random
```


```{r sire-offspring graph}

}

```

```{r number of females per polygynous territories}

```


```{r precocial vs. altricial species}
prec.alt <- function(simul,ticks,trees.seq,tree.distribution,dist.trees,num.males,num.fem,fem.min.resources,age.dispersal){
  df.PTM <- data.frame(matrix(nrow=(length(trees.seq)),ncol=5))
  names(df.PTM) <- c("Initial.trees", "Average Resources", "Resources Distribution", "Poly.success", "Age of Dispersal")
  for (i in 1:length(trees.seq)){
  trees <- trees.seq[i]
  NLCommand(paste("set total-trees ", trees), "setup")
  NLCommand(paste("set distance-trees ", dist.trees), "setup")
  # Distribution: 1 = uniform, 2 = clumped, 3 = random
  NLCommand(paste("set distribution ", tree.distribution), "setup")
  NLCommand(paste("set initial-males ", num.males), "setup")
  NLCommand(paste("set initial-females ", num.fem), "setup")
  NLCommand(paste("set female-min-resources ", fem.min.resources), "setup")
  NLCommand(paste("set age-of-dispersal ", age.dispersal), "setup")
  NLCommand(paste("while [ticks < ", ticks),"] [go]") 
  monogamous.fem.success <- as.numeric(NLReport("sum mono-females-rep-success"))
  polygynous.fem.success <- as.numeric(NLReport("sum poly-females-rep-success"))
  average.resources.total <- as.numeric(NLReport("mean resource-abundance-list"))
  df.PTM[i,]<-c(trees, average.resources.total, tree.distribution, polygynous.fem.success, age.dispersal)
  }   
  return(df.PTM)
}

trees.seq<-seq(100,500,50)

dispersal.10<-prec.alt(1,100,trees.seq,2, 0.25, 24, 100, 10,5)
dispersal.20<-prec.alt(1,100,trees.seq,2, 0.25, 24, 100, 10,10)
dispersal.30<-prec.alt(1,100,trees.seq,2, 0.25, 24, 100, 10,20)
dispersal.40<-prec.alt(1,100,trees.seq,2, 0.25, 24, 100, 10,40)
dispersal.50<-prec.alt(1,100,trees.seq,2, 0.25, 24, 100, 10,80)
plot.dispersal<-ggplot() + geom_smooth (data = dispersal.10, aes(x = Initial.trees, y = Poly.success), colour = "blue", size = 2) + geom_smooth (data = dispersal.20, aes(x = Initial.trees, y = Poly.success), colour = "green", size = 2) + geom_smooth (data = dispersal.30, aes(x = Initial.trees, y = Poly.success), colour = "purple", size = 2) + geom_smooth (data = dispersal.40, aes(x = Initial.trees, y = Poly.success), colour = "yellow", size = 2) + geom_smooth (data = dispersal.50, aes(x = Initial.trees, y = Poly.success), colour = "red", size = 2) + xlab("Abundance of Resources") + ylab("Female Reproductive Success") + theme(axis.title=element_text(size=22), axis.text=element_text(size=14))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
plot.dispersal

```


To quit the Netlogo Flocking model:
```{r Quit Netlogo}
NLQuit()
```


